AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.7

inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Naming:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
